DROP TABLE IF EXISTS temporaire.tmp_bien_couts;
DROP TABLE IF EXISTS siep.bien_couts;
CREATE TABLE IF NOT EXISTS siep.bien_couts (
    id BIGSERIAL,
    code_bat_ter BIGINT NOT NULL,
    annee_charges_copropriete INTEGER,
    annee_charges_locatives INTEGER,
    annee_loyers_budgetaires INTEGER,
    annee1_charges_fonct INTEGER,
    annee1_loyer_ht_hc_ttc FLOAT,
    annee2_charges_fonc FLOAT,
    annee2_loyer_ht_hc_ttc FLOAT,
    charges_copropriete FLOAT,
    charges_fonc_annee2 FLOAT,
    charges_fonc_annee1 FLOAT,
    charges_locatives FLOAT,
    codhc_surfacique_sub FLOAT,
    loyer_surfacique_sub FLOAT,
    loyer_annuel_ht_annee1 FLOAT,
    loyer_annuel_ht_annee2 FLOAT,
    loyer_budgetaire_ttc FLOAT,
    loyer_hc_ttc_annee1 FLOAT,
    loyer_hc_ttc_annee2 FLOAT,
    loyers_budgetaires_2018 FLOAT,
    plafond_loyer_surfacique_sub FLOAT,
    import_timestamp TIMESTAMP NOT NULL,
    import_date DATE NOT NULL,
	snapshot_id TEXT,
    PRIMARY KEY (code_bat_ter, import_timestamp),
    FOREIGN KEY(code_bat_ter, import_timestamp) REFERENCES siep.bien(code_bat_ter, import_timestamp)
) PARTITION BY RANGE (import_timestamp);
