from src._types.projet import SelecteurStorageOptions

selecteur_options = {
    "abonnes_lettres": SelecteurStorageOptions(),
    "collab_inter_structure": SelecteurStorageOptions(),
    "communique_presse": SelecteurStorageOptions(),
    "engagement_agents_mef": SelecteurStorageOptions(),
    "engagement_environnement": SelecteurStorageOptions(),
    "enquete_360": SelecteurStorageOptions(),
    "enquete_satisfaction": SelecteurStorageOptions(),
    "etudes": SelecteurStorageOptions(),
    "grist_doc": SelecteurStorageOptions(
        write_to_s3_with_iceberg=False, write_to_db=False
    ),
    "impact_actions_com": SelecteurStorageOptions(),
    "impressions_reseaux_sociaux": SelecteurStorageOptions(),
    "indicateurs_metiers": SelecteurStorageOptions(),
    "notes_veilles": SelecteurStorageOptions(),
    "obs_interne": SelecteurStorageOptions(),
    "obs_interne_participation": SelecteurStorageOptions(),
    "ouverture_lettre_alize": SelecteurStorageOptions(),
    "performances_lettres": SelecteurStorageOptions(),
    "projets_graphiques": SelecteurStorageOptions(),
    "qualite_vie_travail": SelecteurStorageOptions(),
    "recommandation_strat": SelecteurStorageOptions(),
    "reseaux_sociaux": SelecteurStorageOptions(),
    "rh_contractuel": SelecteurStorageOptions(),
    "rh_formation": SelecteurStorageOptions(),
    "rh_turnover": SelecteurStorageOptions(),
    "studio_graphique": SelecteurStorageOptions(),
    "synthese_depenses": SelecteurStorageOptions(),
    "visites_alize": SelecteurStorageOptions(),
    "visites_bercyinfo": SelecteurStorageOptions(),
    "visites_intranet_sg": SelecteurStorageOptions(),
    "visites_portail": SelecteurStorageOptions(),
}
