from modules.enums.database import LoadStrategy
from modules.types.projet import SelecteurStorageOptions

storage_options = {
    "abonnes_lettres": SelecteurStorageOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "collab_inter_structure": SelecteurStorageOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "communique_presse": SelecteurStorageOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "engagement_agents_mef": SelecteurStorageOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "engagement_environnement": SelecteurStorageOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "enquete_360": SelecteurStorageOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "enquete_satisfaction": SelecteurStorageOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "etudes": SelecteurStorageOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "grist_doc": SelecteurStorageOptions(write_to_s3_with_iceberg=False, write_to_db=False),
    "impact_actions_com": SelecteurStorageOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "impressions_reseaux_sociaux": SelecteurStorageOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "indicateurs_metiers": SelecteurStorageOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "notes_veilles": SelecteurStorageOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "obs_interne": SelecteurStorageOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "obs_interne_participation": SelecteurStorageOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "ouverture_lettre_alize": SelecteurStorageOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "performances_lettres": SelecteurStorageOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "projets_graphiques": SelecteurStorageOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "qualite_vie_travail": SelecteurStorageOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "recommandation_strat": SelecteurStorageOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "reseaux_sociaux": SelecteurStorageOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "rh_contractuel": SelecteurStorageOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "rh_formation": SelecteurStorageOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "rh_turnover": SelecteurStorageOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "studio_graphique": SelecteurStorageOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "synthese_depenses": SelecteurStorageOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "visites_alize": SelecteurStorageOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "visites_bercyinfo": SelecteurStorageOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "visites_intranet_sg": SelecteurStorageOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "visites_portail": SelecteurStorageOptions(load_strategy=LoadStrategy.FULL_LOAD),
}
