from modules.domain.pipeline.model import ExecutionOptions, LoadStrategy

execution_options = {
    "abonnes_aux_lettres": ExecutionOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "collab_inter_structures": ExecutionOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "communique_presse": ExecutionOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "engagement_agents_mef": ExecutionOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "engagement_environnement": ExecutionOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "enquete_360": ExecutionOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "enquete_satisfaction": ExecutionOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "etudes": ExecutionOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "grist_doc": ExecutionOptions(),
    "impact_actions_com": ExecutionOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "impressions_reseaux_sociaux": ExecutionOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "indicateurs_metiers": ExecutionOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "notes_veilles": ExecutionOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "observatoire_interne": ExecutionOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "participation_observatoire_interne": ExecutionOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "ouverture_lettres_alize": ExecutionOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "performances_lettres": ExecutionOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "projets_graphiques": ExecutionOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "qualite_de_vie_au_travail": ExecutionOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "recommandation_strat": ExecutionOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "abonnes_reseaux_sociaux": ExecutionOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "rh_contractuel": ExecutionOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "rh_formation": ExecutionOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "rh_turnover": ExecutionOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "creation_graphique": ExecutionOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "synthese_depenses": ExecutionOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "visites_alize": ExecutionOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "visites_bercyinfo": ExecutionOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "visites_intranet_sg": ExecutionOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "visites_portail": ExecutionOptions(load_strategy=LoadStrategy.FULL_LOAD),
}
