DROP TABLE IF EXISTS siep.declaration_ademe_detail;
CREATE TABLE IF NOT EXISTS siep.declaration_ademe_detail (
    id SERIAL PRIMARY KEY,
    id_consommation INTEGER REFERENCES siep.declaration_ademe(id_consommation),
    ref_operat_efa TEXT,
    annee_declaree TEXT,
    date_debut_conso_reference DATE,
    categorie_activite_principale TEXT,
    vehi_elec_nb_bornes INTEGER,
    vehi_elec_conso_avc_irve_kwh DOUBLE PRECISION,
    conso_indi_hors_irve_kwh DOUBLE PRECISION,
    conso_indi_gaz_nat_reseaux_kwh DOUBLE PRECISION,
    conso_indi_gaz_nat_liquefie_kg DOUBLE PRECISION,
    conso_indi_gaz_propane_kg DOUBLE PRECISION,
    conso_indi_gaz_propane_m3 DOUBLE PRECISION,
    conso_indi_gaz_butane_kg DOUBLE PRECISION,
    conso_indi_gaz_butane_m3 DOUBLE PRECISION,
    conso_indi_fioul_domesti_litre DOUBLE PRECISION,
    conso_indi_charbon_agglo_briq_kg DOUBLE PRECISION,
    conso_indi_houille_kg DOUBLE PRECISION,
    conso_indi_bois_plaq_industrie_kg DOUBLE PRECISION,
    conso_indi_bois_plaq_forest_kg DOUBLE PRECISION,
    conso_indi_bois_gran_briq_kg DOUBLE PRECISION,
    conso_indi_bois_buches_stere DOUBLE PRECISION,
    conso_indi_reseau_chaleur_kwh DOUBLE PRECISION,
    conso_indi_reseau_froid_kwh DOUBLE PRECISION,
    conso_indi_gazole_non_routier_litre DOUBLE PRECISION,
    conso_rep_hors_irve_kwh DOUBLE PRECISION,
    conso_rep_gaz_nat_reseaux_kwh DOUBLE PRECISION,
    conso_rep_gaz_nat_liquefie_kg DOUBLE PRECISION,
    conso_rep_gaz_propane_kg DOUBLE PRECISION,
    conso_rep_gaz_propane_m3 DOUBLE PRECISION,
    conso_rep_gaz_butane_kg DOUBLE PRECISION,
    conso_rep_gaz_butane_m3 DOUBLE PRECISION,
    conso_rep_fioul_domesti_litre DOUBLE PRECISION,
    conso_rep_charbon_agglo_briq_kg DOUBLE PRECISION,
    conso_rep_houille_kg DOUBLE PRECISION,
    conso_rep_bois_plaq_industrie_kg DOUBLE PRECISION,
    conso_rep_bois_plaq_forest_kg DOUBLE PRECISION,
    conso_rep_bois_gran_briq_kg DOUBLE PRECISION,
    conso_rep_bois_buches_stere DOUBLE PRECISION,
    conso_rep_reseau_chaleur_kwh DOUBLE PRECISION,
    conso_rep_reseau_froid_kwh DOUBLE PRECISION,
    conso_rep_gazole_non_routier_litre DOUBLE PRECISION,
    conso_com_hors_irve_kwh DOUBLE PRECISION,
    conso_com_gaz_nat_reseaux_kwh DOUBLE PRECISION,
    conso_com_gaz_nat_liquefie_kg DOUBLE PRECISION,
    conso_com_gaz_propane_kg DOUBLE PRECISION,
    conso_com_gaz_propane_m3 DOUBLE PRECISION,
    conso_com_gaz_butane_kg DOUBLE PRECISION,
    conso_com_gaz_butane_m3 DOUBLE PRECISION,
    conso_com_fioul_domesti_litre DOUBLE PRECISION,
    conso_com_charbon_agglo_briq_kg DOUBLE PRECISION,
    conso_com_houille_kg DOUBLE PRECISION,
    conso_com_bois_plaq_industrie_kg DOUBLE PRECISION,
    conso_com_bois_plaq_forest_kg DOUBLE PRECISION,
    conso_com_bois_gran_briq_kg DOUBLE PRECISION,
    conso_com_bois_buches_stere DOUBLE PRECISION,
    conso_com_reseau_chaleur_kwh DOUBLE PRECISION,
    conso_com_reseau_froid_kwh DOUBLE PRECISION,
    conso_com_gazole_non_routier_litre DOUBLE PRECISION,
    station_meteo_efa DOUBLE PRECISION,
    chauffage_conso_elec_kwh DOUBLE PRECISION,
    chauffage_conso_gaz_nat_reseaux_kwh DOUBLE PRECISION,
    chauffage_conso_gaz_nat_liquefie_kg DOUBLE PRECISION,
    chauffage_conso_gaz_propane_kg DOUBLE PRECISION,
    chauffage_conso_gaz_propane_m3 DOUBLE PRECISION,
    chauffage_conso_gaz_butane_kg DOUBLE PRECISION,
    chauffage_conso_gaz_butane_m3 DOUBLE PRECISION,
    chauffage_conso_fioul_domesti_litre DOUBLE PRECISION,
    chauffage_conso_charbon_agglo_briq_kg DOUBLE PRECISION,
    chauffage_conso_houille_kg DOUBLE PRECISION,
    chauffage_conso_bois_plaq_industrie_kg DOUBLE PRECISION,
    chauffage_conso_bois_plaq_forest_kg DOUBLE PRECISION,
    chauffage_conso_bois_gran_briq_kg DOUBLE PRECISION,
    chauffage_conso_bois_buches_stere DOUBLE PRECISION,
    chauffage_conso_reseau_chaleur_kwh DOUBLE PRECISION,
    chauffage_conso_reseau_froid_kwh DOUBLE PRECISION,
    chauffage_conso_gazole_non_routier_litre DOUBLE PRECISION,
    refroidissement_conso_elec_kwh DOUBLE PRECISION,
    refroidissement_conso_gaz_nat_reseaux_kwh DOUBLE PRECISION,
    refroidissement_conso_gaz_nat_liquefie_kg DOUBLE PRECISION,
    refroidissement_conso_gaz_propane_kg DOUBLE PRECISION,
    refroidissement_conso_gaz_propane_m3 DOUBLE PRECISION,
    refroidissement_conso_gaz_butane_kg DOUBLE PRECISION,
    refroidissement_conso_gaz_butane_m3 DOUBLE PRECISION,
    refroidissement_conso_fioul_domesti_litre DOUBLE PRECISION,
    refroidissement_conso_charbon_agglo_briq_kg DOUBLE PRECISION,
    refroidissement_conso_houille_kg DOUBLE PRECISION,
    refroidissement_conso_bois_plaq_industrie_kg DOUBLE PRECISION,
    refroidissement_conso_bois_plaq_forest_kg DOUBLE PRECISION,
    refroidissement_conso_bois_gran_briq_kg DOUBLE PRECISION,
    refroidissement_conso_bois_buches_stere DOUBLE PRECISION,
    refroidissement_conso_reseau_chaleur_kwh DOUBLE PRECISION,
    refroidissement_conso_reseau_froid_kwh DOUBLE PRECISION,
    refroidissement_conso_gazole_non_routier_litre DOUBLE PRECISION,
    froid_logist_hauteur_refroidie DOUBLE PRECISION,
    froid_logist_conso_elec_kwh DOUBLE PRECISION,
    froid_logist_conso_gaz_nat_reseaux_kwh DOUBLE PRECISION,
    froid_logist_conso_gaz_nat_liquefie_kg DOUBLE PRECISION,
    froid_logist_conso_gaz_propane_kg DOUBLE PRECISION,
    froid_logist_conso_gaz_propane_m3 DOUBLE PRECISION,
    froid_logist_conso_gaz_butane_kg DOUBLE PRECISION,
    froid_logist_conso_gaz_butane_m3 DOUBLE PRECISION,
    froid_logist_conso_fioul_domesti_litre DOUBLE PRECISION,
    froid_logist_conso_charbon_agglo_briq_kg DOUBLE PRECISION,
    froid_logist_conso_houille_kg DOUBLE PRECISION,
    froid_logist_conso_bois_plaq_industrie_kg DOUBLE PRECISION,
    froid_logist_conso_bois_plaq_forest_kg DOUBLE PRECISION,
    froid_logist_conso_bois_gran_briq_kg DOUBLE PRECISION,
    froid_logist_conso_bois_buches_stere DOUBLE PRECISION,
    froid_logist_conso_reseau_chaleur_kwh DOUBLE PRECISION,
    froid_logist_conso_reseau_froid_kwh DOUBLE PRECISION,
    froid_logist_conso_gazole_non_routier_litre DOUBLE PRECISION,
    froid_com_conso_elec_kwh DOUBLE PRECISION,
    froid_com_conso_gaz_nat_reseaux_kwh DOUBLE PRECISION,
    froid_com_conso_gaz_nat_liquefie_kg DOUBLE PRECISION,
    froid_com_conso_gaz_propane_kg DOUBLE PRECISION,
    froid_com_conso_gaz_propane_m3 DOUBLE PRECISION,
    froid_com_conso_gaz_butane_kg DOUBLE PRECISION,
    froid_com_conso_gaz_butane_m3 DOUBLE PRECISION,
    froid_com_conso_fioul_domesti_litre DOUBLE PRECISION,
    froid_com_conso_charbon_agglo_briq_kg DOUBLE PRECISION,
    froid_com_conso_houille_kg DOUBLE PRECISION,
    froid_com_conso_bois_plaq_industrie_kg DOUBLE PRECISION,
    froid_com_conso_bois_plaq_forest_kg DOUBLE PRECISION,
    froid_com_conso_bois_gran_briq_kg DOUBLE PRECISION,
    froid_com_conso_bois_buches_stere DOUBLE PRECISION,
    froid_com_conso_reseau_chaleur_kwh DOUBLE PRECISION,
    froid_com_conso_reseau_froid_kwh DOUBLE PRECISION,
    froid_com_conso_gazole_non_routier_litre DOUBLE PRECISION,
    conservation_doc_conso_elec_kwh DOUBLE PRECISION,
    conservation_doc_conso_gaz_nat_reseaux_kwh DOUBLE PRECISION,
    conservation_doc_conso_gaz_nat_liquefie_kg DOUBLE PRECISION,
    conservation_doc_conso_gaz_propane_kg DOUBLE PRECISION,
    conservation_doc_conso_gaz_propane_m3 DOUBLE PRECISION,
    conservation_doc_conso_gaz_butane_kg DOUBLE PRECISION,
    conservation_doc_conso_gaz_butane_m3 DOUBLE PRECISION,
    conservation_doc_conso_fioul_domesti_litre DOUBLE PRECISION,
    conservation_doc_conso_charbon_agglo_briq_kg DOUBLE PRECISION,
    conservation_doc_conso_houille_kg DOUBLE PRECISION,
    conservation_doc_conso_bois_plaq_industrie_kg DOUBLE PRECISION,
    conservation_doc_conso_bois_plaq_forest_kg DOUBLE PRECISION,
    conservation_doc_conso_bois_gran_briq_kg DOUBLE PRECISION,
    conservation_doc_conso_bois_buches_stere DOUBLE PRECISION,
    conservation_doc_conso_reseau_chaleur_kwh DOUBLE PRECISION,
    conservation_doc_conso_reseau_froid_kwh DOUBLE PRECISION,
    conservation_doc_conso_gazole_non_routier_litre DOUBLE PRECISION
);

DROP TABLE IF EXISTS siep.declaration_ademe_activite;
CREATE TABLE IF NOT EXISTS siep.declaration_ademe_activite (
    id SERIAL PRIMARY KEY,
    id_consommation INTEGER REFERENCES siep.declaration_ademe(id_consommation),
    sous_categorie_activite TEXT,
    surface_plancher_m2 INTEGER,
    date_debut_activite DATE,
    date_fin_activite DATE,
    chauffage TEXT,
    refroidissement TEXT,
    logistique_de_froid TEXT,
    froid_commercial TEXT,
    conservation_doc_collections TEXT,
    nb_jours_occupes_mois_1 DOUBLE PRECISION,
    nb_jours_occupes_mois_2 DOUBLE PRECISION,
    nb_jours_occupes_mois_3 DOUBLE PRECISION,
    nb_jours_occupes_mois_4 DOUBLE PRECISION,
    nb_jours_occupes_mois_5 DOUBLE PRECISION,
    nb_jours_occupes_mois_6 DOUBLE PRECISION,
    nb_jours_occupes_mois_7 DOUBLE PRECISION,
    nb_jours_occupes_mois_8 DOUBLE PRECISION,
    nb_jours_occupes_mois_9 DOUBLE PRECISION,
    nb_jours_occupes_mois_10 DOUBLE PRECISION,
    nb_jours_occupes_mois_11 DOUBLE PRECISION,
    nb_jours_occupes_mois_12 DOUBLE PRECISION,
    nb_jours_occupes_mois_13 DOUBLE PRECISION,
    total_nb_jours_occupes DOUBLE PRECISION
);


DROP TABLE IF EXISTS siep.declaration_ademe_indicateur;
CREATE TABLE IF NOT EXISTS siep.declaration_ademe_indicateur (
    id SERIAL PRIMARY KEY,
    id_consommation INTEGER REFERENCES siep.declaration_ademe(id_consommation),
    num_indicateur INTEGER,
    nom_indicateur TEXT,
    valeur_indicateur DOUBLE PRECISION
);
