from modules.domain.pipeline.model import ExecutionOptions, LoadStrategy

execution_options = {
    "delai_global_paiement_sp_manuel": ExecutionOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "demande_achat_sp_manuel": ExecutionOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "demande_paiement_sp_manuel": ExecutionOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "engagement_juridique_sp_manuel": ExecutionOptions(load_strategy=LoadStrategy.FULL_LOAD),
    "get_all_cf_cc": ExecutionOptions(),
    "get_delai_global_paiement": ExecutionOptions(),
    "get_demande_achat": ExecutionOptions(),
    "get_demande_paiement_complet": ExecutionOptions(),
    "get_engagement_juridique": ExecutionOptions(),
    "grist_doc": ExecutionOptions(),
    "load_delai_global_paiement": ExecutionOptions(),
    "load_demande_achat": ExecutionOptions(),
    "load_demande_paiement_complet": ExecutionOptions(),
    "load_engagement_juridique": ExecutionOptions(),
    "load_new_cf_cc": ExecutionOptions(),
    "ref_bop": ExecutionOptions(),
    "ref_cc": ExecutionOptions(),
    "ref_prog": ExecutionOptions(),
    "ref_sdep": ExecutionOptions(),
    "ref_sp_choisi": ExecutionOptions(),
    "ref_sp_pilotage": ExecutionOptions(),
    "ref_uo": ExecutionOptions(),
    "sp": ExecutionOptions(load_strategy=LoadStrategy.FULL_LOAD),
}
